server: server.c
	gcc -static -static-libgcc -static-libstdc++ -fno-stack-protector -no-pie server.c -o server
IWantToKnowMoreAboutYou:
	gcc -static -static-libgcc -static-libstdc++ -fno-stack-protector -no-pie IWantToKnowMoreAboutYou.c -o IWantToKnowMoreAboutYou
